/* Private attachments: normalize picker types, bound photos, chunk large uploads and cache viewed files. */
window.TripAttachments=(()=>{
 const LIMIT=10*1024*1024,PHOTO_LIMIT=1024*1024,MAX_CACHE=50*1024*1024;
 const extensions={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',m4a:'audio/mp4',mp3:'audio/mpeg',aac:'audio/aac',wav:'audio/wav',ogg:'audio/ogg',webm:'audio/webm',flac:'audio/flac',pdf:'application/pdf',txt:'text/plain',zip:'application/zip',doc:'application/msword',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',xls:'application/vnd.ms-excel',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',ppt:'application/vnd.ms-powerpoint',pptx:'application/vnd.openxmlformats-officedocument.presentationml.presentation'};
 const types=new Set(Object.values(extensions));let database;const pending=new Map();
 const scope=()=>localStorage.getItem('trip-room')||'legacy';
 function mime(file,kind){const ext=file.name.split('.').pop().toLowerCase();let type=file.type.split(';')[0].toLowerCase();type=({'audio/mp3':'audio/mpeg','audio/m4a':'audio/mp4','audio/x-wav':'audio/wav','application/x-zip-compressed':'application/zip'})[type]||type;if(!types.has(type))type=extensions[ext]||'';if(!type&&kind==='photo')type='image/jpeg';if(!type&&kind==='audio')throw Error('Не удалось определить формат записи. Выбери MP3, M4A, WAV или OGG.');return type||'application/octet-stream';}
 async function image(file){if(window.createImageBitmap){try{return await createImageBitmap(file);}catch(_){}}const url=URL.createObjectURL(file);try{return await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('Фото не открывается. Выбери JPEG, PNG или WebP; HEIC можно отправить файлом.'));image.src=url;});}finally{URL.revokeObjectURL(url);}}
 async function prepare(file,kind){if(!file.size)throw Error('Файл пустой или недоступен. Выбери его снова.');const type=mime(file,kind);if(kind==='photo'||type.startsWith('image/')){const source=await image(file);try{const canvas=document.createElement('canvas');let edge=1600;for(let attempt=0;attempt<5;attempt++){const scale=Math.min(1,edge/Math.max(source.width,source.height));canvas.width=Math.max(1,Math.round(source.width*scale));canvas.height=Math.max(1,Math.round(source.height*scale));canvas.getContext('2d').drawImage(source,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',Math.max(.6,.86-attempt*.06)));if(blob&&blob.size<=PHOTO_LIMIT)return blob;edge=Math.round(edge*.8);}throw Error('Не удалось уменьшить фото. Выбери другое изображение.');}finally{source.close?.();}}if(file.size>LIMIT)throw Error('Файл больше 10 МБ. Выбери меньший файл или более короткую запись.');return file.slice(0,file.size,type);}
 const base64=blob=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=()=>reject(Error('Не удалось прочитать файл. Выбери его снова.'));reader.readAsDataURL(blob);});
 async function retry(path,body){let error;for(let attempt=0;attempt<3;attempt++){try{return await TripSync.call(path,{method:'POST',body:JSON.stringify(body)});}catch(e){error=e;if(!navigator.onLine||['400','401','403','413'].includes(e.message))throw e;await new Promise(r=>setTimeout(r,250*(attempt+1)));}}throw error;}
 async function upload(file,kind,progress){const blob=await prepare(file,kind);let result;if(blob.size<=PHOTO_LIMIT){progress(0);result=await retry('/api/media',{mime:blob.type,data:await base64(blob)});}else{const start=await retry('/api/media/start',{mime:blob.type,bytes:blob.size});for(let part=0;part<start.parts;part++){await retry('/api/media/chunk',{id:start.id,part,data:await base64(blob.slice(part*start.chunkBytes,Math.min(blob.size,(part+1)*start.chunkBytes)))});progress(Math.round((part+1)/start.parts*100));}result=await retry('/api/media/complete',{id:start.id});}progress(100);return {...result,name:file.name,bytes:blob.size};}
 function db(){if(database)return database;database=new Promise(resolve=>{if(!window.indexedDB){resolve(null);return;}const request=indexedDB.open('trip-private-media',1);request.onupgradeneeded=()=>request.result.createObjectStore('files',{keyPath:'key'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>resolve(null);request.onblocked=()=>resolve(null);});return database;}
 async function cached(key){try{const database=await db();if(!database)return null;return await new Promise(resolve=>{const request=database.transaction('files').objectStore('files').get(key);request.onsuccess=()=>resolve(request.result?.blob||null);request.onerror=()=>resolve(null);});}catch(_){return null;}}
 async function cache(key,blob){try{const database=await db();if(!database)return;await new Promise(resolve=>{const transaction=database.transaction('files','readwrite');transaction.objectStore('files').put({key,blob,bytes:blob.size,at:Date.now()});transaction.oncomplete=transaction.onerror=transaction.onabort=resolve;});const transaction=database.transaction('files','readwrite'),store=transaction.objectStore('files'),request=store.getAll();request.onsuccess=()=>{const rows=request.result.sort((a,b)=>a.at-b.at);let bytes=rows.reduce((sum,row)=>sum+row.bytes,0);for(const row of rows){if(bytes<=MAX_CACHE)break;store.delete(row.key);bytes-=row.bytes;}};}catch(_){} }
 async function get(media){const key=scope()+'|'+media.id;if(pending.has(key))return pending.get(key);const job=(async()=>{const saved=await cached(key);if(saved)return saved;const token=localStorage.getItem('trip-access')||window.TripNative?.getSyncAccess?.()||'';const response=await fetch('https://trip-private.ivan-s-2001.workers.dev/api/media/'+media.id,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(30000)});if(!response.ok)throw Error('Вложение недоступно');const blob=await response.blob();if(blob.size>LIMIT)throw Error('Файл слишком большой');await cache(key,blob);return blob;})();pending.set(key,job);try{return await job;}finally{pending.delete(key);}}
 return {prepare,upload,get,mime};
})();
