(()=>{
const $=id=>document.getElementById(id),qa=new URLSearchParams(location.search).get('qa')==='1';let mounted=false,editing=null,media=[],messages=[],busy=false,objectUrls=[],requestId=crypto.randomUUID();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=d=>new Date(d).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'});
function mount(){if(mounted)return;mounted=true;
$('messageComposer').innerHTML=`<h2>Сообщение для Наташи</h2><label>Твои подготовленные сообщения<select id="preparedMessage"><option value="">Новое сообщение</option></select></label><form id="composeForm"><label>Название<input id="composeTitle" maxlength="160" required placeholder="Солнышко, кое-что для тебя…"></label><label>Текст<textarea id="composeText" rows="6" maxlength="20000" placeholder="Напиши от души"></textarea></label><label>Как открыть<select id="composeType"><option value="none">Сразу показать</option><option value="letter">Открыть письмо</option><option value="gift">Распаковать подарок</option><option value="hold">Зажать и открыть</option><option value="hug">Секунды объятий</option><option value="choice">Выбрать ответ</option></select></label><label id="choicesLabel" hidden>Варианты ответа, каждый с новой строки<textarea id="composeChoices" rows="4"></textarea></label><label>Фотографии — до 10<input id="composePhotos" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><label>Голосовое<input id="composeAudio" type="file" accept="audio/mp4,audio/mpeg,audio/ogg,audio/webm,.m4a"></label><div id="composeMedia"></div><label>Когда<select id="composeWhen"><option value="now">Отправить сейчас</option><option value="later">В определённое время</option></select></label><label id="dateLabel" hidden>Дата и время по Москве<input id="composeDate" type="datetime-local"></label><div class="compose-buttons"><button class="primary" id="composeSubmit" type="submit">Отправить сейчас</button><button id="composeReset" type="button">Очистить</button></div><p id="composeStatus" role="status"></p></form>`;
const prepared=Object.entries(window.TRIP_CONTENT.days).flatMap(([day,items])=>items.filter(item=>item.id>=1&&item.id<=12).map(item=>({...item,day})));
 for(const item of prepared){const option=document.createElement('option');option.value=item.id;option.textContent=`${item.day} октября · ${item.title}`;$('preparedMessage').append(option);}
 $('preparedMessage').onchange=async()=>{if(busy)return;const item=prepared.find(x=>String(x.id)===$('preparedMessage').value);if(!item)return;reset();$('composeTitle').value=item.title;$('composeText').value=Array.isArray(item.text)?item.text.join('\n'):item.text||'';$('composeType').value=item.type==='question'?'choice':item.type==='hug-seconds'||item.type==='hug'?'hug':item.type.startsWith('gift')?'gift':item.type.startsWith('letter')?'letter':'none';$('composeType').onchange();$('composeChoices').value=(item.choices||[]).join('\n');$('composeForm').dispatchEvent(new Event('input'));const files=Array.isArray(item.media)?item.media:item.media?[item.media]:[];try{const attachments=[];for(const file of files){const folder=item.type==='voice'?'audio':'photos';const response=await fetch('./assets/'+folder+'/'+file);if(!response.ok)throw Error();attachments.push(new File([await response.blob()],file,{type:item.type==='voice'?'audio/mp4':'image/jpeg'}));}if(attachments.length)await upload(attachments);}catch(_){status('Текст подготовлен, но вложения не загрузились. Попробуй выбрать сообщение ещё раз.');}};
 $('composeType').onchange=()=>$('choicesLabel').hidden=$('composeType').value!=='choice';
$('composeWhen').onchange=()=>{const later=$('composeWhen').value==='later';$('dateLabel').hidden=!later;$('composeDate').required=later;$('composeSubmit').textContent=later?'Запланировать':'Отправить сейчас';};
$('composeReset').onclick=reset;
$('composePhotos').onchange=async e=>{const files=[...e.target.files];if(media.filter(m=>m.mime.startsWith('image/')).length+files.length>10){status('Можно прикрепить до 10 фотографий.');return;}await upload(files);e.target.value='';};
$('composeAudio').onchange=async e=>{if(media.some(m=>m.mime.startsWith('audio/'))){status('Сначала убери прежнее голосовое.');return;}await upload([...e.target.files]);e.target.value='';};
$('composeForm').onsubmit=send;
 const persist=()=>localStorage.setItem('trip-composer-draft',JSON.stringify({title:$('composeTitle').value,text:$('composeText').value,type:$('composeType').value,choices:$('composeChoices').value,when:$('composeWhen').value,date:$('composeDate').value,media,requestId,editing}));
 $('composeForm').addEventListener('input',persist);$('composeForm').addEventListener('change',persist);
 try{const d=JSON.parse(localStorage.getItem('trip-composer-draft'));if(d){$('composeTitle').value=d.title;$('composeText').value=d.text;$('composeType').value=d.type;$('composeChoices').value=d.choices;$('composeWhen').value=d.when;$('composeDate').value=d.date;media=d.media||[];requestId=d.requestId||requestId;editing=d.editing;$('composeType').onchange();$('composeWhen').onchange();renderMedia();}}catch(_){}

}
function status(s){$('composeStatus').textContent=s;}
function reset(){localStorage.removeItem("trip-composer-draft");requestId=crypto.randomUUID();editing=null;media=[];$('composeForm').reset();$('dateLabel').hidden=$('choicesLabel').hidden=true;$('composeDate').required=false;$('composeSubmit').textContent='Отправить сейчас';renderMedia();status('');}
async function photo(file){const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas');const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));canvas.width=bitmap.width*scale;canvas.height=bitmap.height*scale;canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.8));}
async function upload(files){if(qa){status("QA: вложения не отправляются на сервер.");return;}if(busy)return;busy=true;$('composeSubmit').disabled=true;try{for(const file of files){status(`Загружаю ${file.name}…`);const blob=file.type.startsWith('image/')?await photo(file):file;if(blob.size>1048576)throw Error('Голосовое должно быть до 1 МБ. Выбери более короткую запись.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(blob);});const mime=blob.type||(/\.m4a$/i.test(file.name)?'audio/mp4':'');const result=await TripSync.call('/api/media',{method:'POST',body:JSON.stringify({mime,data})});media.push({...result,name:file.name});renderMedia();$('composeForm').dispatchEvent(new Event('input'));}status('Вложения готовы.');}catch(e){status(e.message.includes('МБ')?e.message:'Не удалось загрузить вложение. Попробуй ещё раз.');}finally{busy=false;$('composeSubmit').disabled=false;}}
function renderMedia(){const root=$('composeMedia');root.replaceChildren();for(const [i,m]of media.entries()){const row=document.createElement('div');row.textContent=m.name||'Вложение';const remove=document.createElement('button');remove.type='button';remove.textContent='Убрать';remove.onclick=()=>{media.splice(i,1);renderMedia();};row.append(remove);root.append(row);}}
async function send(e){e.preventDefault();if(busy)return;const choices=$('composeChoices').value.split('\n').map(s=>s.trim()).filter(Boolean),interactive=$('composeType').value;
if(interactive==='choice'&&(choices.length<2||choices.length>6)){status('Добавь от 2 до 6 вариантов ответа.');return;}
const later=$('composeWhen').value==='later',due=later?Date.parse($('composeDate').value+':00+03:00'):Date.now();if(!Number.isFinite(due)||later&&due<=Date.now()){status('Выбери время в будущем по Москве.');return;}
busy=true;$('composeSubmit').disabled=true;try{await TripSync.call('/api/messages',{method:'POST',body:JSON.stringify({id:editing||undefined,requestId,title:$('composeTitle').value,text:$('composeText').value,interactive,choices,media,due})});reset();status(later?'Сообщение запланировано.':'Сообщение отправлено на сервер.');await list();}catch(e){status(e.message==='409'?'Сообщение уже доступно Наташе. Его нельзя изменить.':'Не удалось отправить. Текст и вложения сохранены в редакторе.');}finally{busy=false;$('composeSubmit').disabled=false;}}
async function list(){const data=await TripSync.call('/api/messages');messages=data.messages;const root=$('sentMessages');root.innerHTML='<h2>Твои сообщения</h2>';for(const m of messages){const card=document.createElement('article');card.innerHTML=`<strong>${esc(m.title)}</strong><p>${esc(m.cancelled?'Отменено':m.due>Date.now()?'Запланировано':'Доступно Наташе')} · ${date(m.due)}</p>`;if(!m.cancelled&&m.due>Date.now()){const edit=document.createElement('button');edit.textContent='Изменить';edit.onclick=()=>{editing=m.id;media=[...m.body.media];$('composeTitle').value=m.title;$('composeText').value=m.body.text;$('composeType').value=m.body.interactive;$('composeType').onchange();$('composeChoices').value=m.body.choices.join('\n');$('composeWhen').value='later';$('composeWhen').onchange();$('composeDate').value=new Date(m.due+10800000).toISOString().slice(0,16);renderMedia();$('composeTitle').focus();};const cancel=document.createElement('button');cancel.textContent='Отменить';cancel.onclick=async()=>{await TripSync.call('/api/messages/cancel',{method:'POST',body:JSON.stringify({id:m.id})});await list();};card.append(edit,cancel);}card.id='received-'+m.id;root.append(card);}}
let inbox=null,openedFromNotification=false,inboxIndex=0;
function inboxMount(){if(inbox)return;$('scene').hidden=true;inbox=document.createElement('main');inbox.className='personal-inbox wife-feed';inbox.innerHTML='<header><p>НАШЕ МЕСТО</p><h2>От Вани ♥</h2><span id="inboxCount"></span></header><div id="inboxMessages"></div><nav><button id="inboxPrev" type="button">← Предыдущее</button><button id="inboxNext" type="button">Следующее →</button></nav>';document.body.append(inbox);$('inboxPrev').onclick=()=>step(-1);$('inboxNext').onclick=()=>step(1);let start=null;inbox.addEventListener('touchstart',e=>{if(e.target.closest('button,input,audio,.inbox-gallery'))return;start={x:e.touches[0].clientX,y:e.touches[0].clientY};},{passive:true});inbox.addEventListener('touchend',e=>{if(!start)return;const dx=e.changedTouches[0].clientX-start.x,dy=e.changedTouches[0].clientY-start.y;start=null;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.3)step(dx<0?1:-1);},{passive:true});}
function step(delta){inboxIndex=Math.max(0,Math.min(messages.length-1,inboxIndex+delta));drawInbox();}
async function loadMedia(node,m){if(qa&&m.path){node.src=m.path;return;}try{const token=localStorage.getItem('trip-access')||window.TripNative?.getSyncAccess?.()||'';const response=await fetch('https://trip-private.ivan-s-2001.workers.dev/api/media/'+m.id,{headers:{Authorization:'Bearer '+token}});if(!response.ok)throw Error();const url=URL.createObjectURL(await response.blob());objectUrls.push(url);node.src=url;}catch(_){node.replaceWith(document.createTextNode('Вложение пока недоступно. Попробуй открыть сообщение снова.'));}}
function drawInbox(){objectUrls.forEach(URL.revokeObjectURL);objectUrls=[];const root=$('inboxMessages');root.replaceChildren();const visible=messages[inboxIndex];$('inboxCount').textContent=messages.length?`${inboxIndex+1} / ${messages.length}`:'Здесь будут твои сообщения';$('inboxPrev').disabled=inboxIndex===0;$('inboxNext').disabled=inboxIndex>=messages.length-1;for(const m of visible?[visible]:[]){const card=document.createElement('article');const title=document.createElement('h3');title.textContent=m.title;card.append(title);const content=document.createElement('div');content.hidden=['letter','gift','hold'].includes(m.body.interactive);const text=document.createElement('p');text.textContent=m.body.text;content.append(text);const gallery=document.createElement('div');gallery.className='inbox-gallery';for(const f of m.body.media){const node=document.createElement(f.mime.startsWith('image/')?'img':'audio');if(node.tagName==='AUDIO')node.controls=true;else node.alt='От Вани';gallery.append(node);loadMedia(node,f);}content.append(gallery);card.append(content);
const key='trip-message-'+m.id,answer=value=>TripSync.save(key,value);
if(content.hidden){const open=document.createElement('button');open.textContent=({letter:'Открыть письмо',gift:'Открыть подарок',hold:'Удерживай две секунды'})[m.body.interactive];const reveal=()=>{content.hidden=false;open.remove();answer('Открыла');};if(m.body.interactive==='hold'){let timer;open.onpointerdown=e=>{open.setPointerCapture(e.pointerId);timer=setTimeout(reveal,2000);};open.onpointerup=open.onpointercancel=open.onlostpointercapture=()=>clearTimeout(timer);open.onkeydown=e=>{if((e.key===' '||e.key==='Enter')&&!e.repeat){e.preventDefault();timer=setTimeout(reveal,2000);}};open.onkeyup=()=>clearTimeout(timer);}else open.onclick=reveal;card.append(open);}else if(!localStorage.getItem(key))answer('Открыла');
if(m.body.interactive==='choice')for(const choice of m.body.choices){const b=document.createElement('button');b.textContent=choice;b.classList.toggle('selected',localStorage.getItem(key)===choice);b.onclick=()=>{answer(choice);card.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));};card.append(b);}
if(m.body.interactive==='hug'){const b=document.createElement('button');let count=Number(localStorage.getItem(key))||0;const label=()=>b.textContent=`Обнимемся ${count} секунд ♥`;label();b.onclick=()=>{count++;label();answer(String(count));};card.append(b);}card.id='received-'+m.id;root.append(card);}}
async function tick(){if(qa){if(new URLSearchParams(location.search).get('inbox')==='1'&&!inbox){messages=Object.values(window.TRIP_CONTENT.days).flat().filter(x=>x.id>=1&&x.id<=12).map(x=>({id:'qa-'+x.id,title:x.title,body:{text:x.text||'',interactive:x.type==='question'?'choice':x.type==='hug-seconds'?'hug':'none',choices:x.choices||[],media:(Array.isArray(x.media)?x.media:x.media?[x.media]:[]).map(file=>({mime:x.type==='voice'?'audio/mp4':'image/jpeg',path:'./assets/'+(x.type==='voice'?'audio/':'photos/')+file}))}}));inboxMount();inbox.querySelector('header p').textContent='QA · ПРЕДПРОСМОТР ЛЕНТЫ';const switcher=document.createElement('button');switcher.textContent='QA: редактор Вани';switcher.onclick=()=>location.search='?qa=1&editor=1';inbox.querySelector('header').append(switcher);drawInbox();}if(new URLSearchParams(location.search).get('editor')==='1'){mount();$('scene').hidden=true;$('husbandDashboard').hidden=false;$('dashboardStatus').textContent='QA · предпросмотр редактора, отправка отключена';if(!document.getElementById('qaFeedSwitch')){const switcher=document.createElement('button');switcher.id='qaFeedSwitch';switcher.textContent='QA: лента Наташи';switcher.onclick=()=>location.search='?qa=1&inbox=1';$('messageComposer').prepend(switcher);}$('composeSubmit').disabled=true;$('composePhotos').disabled=true;$('composeAudio').disabled=true;$('composeForm').onsubmit=e=>e.preventDefault();}return;}try{if(TripSync.getRole()==='husband'){mount();await list();}else if(TripSync.getRole()==='wife'){const data=await TripSync.call('/api/messages');const previous=messages[inboxIndex]?.id;const changed=JSON.stringify(messages)!==JSON.stringify(data.messages);messages=data.messages;inboxMount();if(previous){const index=messages.findIndex(m=>m.id===previous);if(index>=0)inboxIndex=index;}if(location.hash.startsWith('#message-')&&!openedFromNotification){openedFromNotification=true;const index=messages.findIndex(m=>m.id===location.hash.slice(9));if(index>=0)inboxIndex=index;}if(changed||!$('inboxMessages').children.length)drawInbox();}}catch(_){}}
document.addEventListener('DOMContentLoaded',()=>{setTimeout(tick,800);setInterval(()=>{if(!document.hidden)tick();},15000);window.addEventListener('online',tick);});
})();
