(()=>{
const $=id=>document.getElementById(id),qa=new URLSearchParams(location.search).get('qa')==='1';let previewUrls=[],mounted=false,editing=null,media=[],messages=[],busy=false,objectUrls=[],requestId=crypto.randomUUID();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=d=>new Date(d).toLocaleString('ru-RU',{timeZone:'Europe/Moscow',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'});
function mount(){if(mounted)return;mounted=true;
$('messageComposer').innerHTML=`<div class="section-heading"><p class="eyebrow">Для Наташи</p><h2>Немного тебя<br>в её дне</h2><p class="field-hint">Письмо, голос или маленький сюрприз.</p></div><label class="prepared-label">Из твоих заготовок<select id="preparedMessage"><option value="">Написать новое</option></select></label><form id="composeForm"><label>Название<input id="composeTitle" maxlength="160" required placeholder="Например, «Когда захочется домой»"></label><label>Твоё письмо<textarea id="composeText" rows="7" maxlength="20000" placeholder="Расскажи, что у тебя. Или просто скажи, что скучаешь."></textarea></label><details class="compose-options"><summary>Фото и голосовое <span id="attachmentCount">по желанию</span></summary><p class="field-hint">До 10 фотографий и одна запись до 1 МБ.</p><div class="attachment-controls"><label class="file-control"><span class="bi-icon bi-camera-fill" aria-hidden="true"></span> Добавить фото<input id="composePhotos" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><label class="file-control"><span class="bi-icon bi-mic-fill" aria-hidden="true"></span> Добавить голос<input id="composeAudio" type="file" accept="audio/mp4,audio/mpeg,audio/ogg,audio/webm,.m4a"></label></div><div id="composeMedia"></div></details><details class="compose-options" id="interactionOptions"><summary>Маленький интерактив <span id="interactionLabel">без интерактива</span></summary><label>Как открыть<select id="composeType"><option value="none">Сразу показать</option><option value="letter">Открыть письмо</option><option value="gift">Распаковать подарок</option><option value="hold">Зажать и открыть</option><option value="hug">Секунды объятий</option><option value="choice">Выбрать ответ</option></select></label><label id="choicesLabel" hidden>Ответы на выбор<textarea id="composeChoices" rows="4" placeholder="Один вариант на строку"></textarea><span class="field-hint">От 2 до 6 вариантов.</span></label></details><div class="delivery-options"><label>Когда отправить<select id="composeWhen"><option value="now">Сейчас</option><option value="later">В выбранное время</option></select></label><label id="dateLabel" hidden>Дата и время по Москве<input id="composeDate" type="datetime-local"></label></div><div class="compose-buttons"><button class="primary" id="composeSubmit" type="submit">Отправить сейчас</button><button id="composePreview" type="button">Посмотреть</button><button id="composeReset" class="text-button" type="button">Очистить</button></div><p id="composeStatus" role="status"></p><p class="draft-note">Черновик сохраняется на этом телефоне.</p></form>`;
const prepared=Object.entries(window.TRIP_CONTENT.days).flatMap(([day,items])=>items.filter(item=>item.id>=1&&item.id<=12).map(item=>({...item,day})));
 for(const item of prepared){const option=document.createElement('option');option.value=item.id;option.textContent=`${item.day} октября · ${item.title}`;$('preparedMessage').append(option);}
 $('preparedMessage').onchange=async()=>{if(busy)return;const item=prepared.find(x=>String(x.id)===$('preparedMessage').value);if(!item)return;reset();$('composeTitle').value=item.title;$('composeText').value=Array.isArray(item.text)?item.text.join('\n'):item.text||'';$('composeType').value=item.type==='question'?'choice':item.type==='hug-seconds'||item.type==='hug'?'hug':item.type.startsWith('gift')?'gift':item.type.startsWith('letter')?'letter':'none';$('composeType').onchange();$('composeChoices').value=(item.choices||[]).join('\n');$('composeForm').dispatchEvent(new Event('input'));const files=Array.isArray(item.media)?item.media:item.media?[item.media]:[];try{const attachments=[];for(const file of files){const folder=item.type==='voice'?'audio':'photos';const response=await fetch('./assets/'+folder+'/'+file);if(!response.ok)throw Error();attachments.push(new File([await response.blob()],file,{type:item.type==='voice'?'audio/mp4':'image/jpeg'}));}if(attachments.length)await upload(attachments);}catch(_){status('Текст подготовлен, но вложения не загрузились. Попробуй выбрать сообщение ещё раз.');}};
 $('composeType').onchange=()=>{const type=$('composeType');$('choicesLabel').hidden=type.value!=='choice';$('interactionLabel').textContent=type.value==='none'?'без интерактива':type.selectedOptions[0].textContent;};
$('composeWhen').onchange=()=>{const later=$('composeWhen').value==='later';$('dateLabel').hidden=!later;$('composeDate').required=later;$('composeSubmit').textContent=later?'Запланировать':'Отправить сейчас';};
$('composeReset').onclick=()=>{if(busy)return;reset();};
$('composePreview').onclick=preview; $('closePreview').onclick=()=>$('messagePreview').close();$('messagePreview').addEventListener('close',()=>{previewUrls.forEach(URL.revokeObjectURL);previewUrls=[];$('previewBody').replaceChildren();});
$('composePhotos').onchange=async e=>{const files=[...e.target.files];if(media.filter(m=>m.mime.startsWith('image/')).length+files.length>10){status('Можно прикрепить до 10 фотографий.');return;}await upload(files);e.target.value='';};
$('composeAudio').onchange=async e=>{if(media.some(m=>m.mime.startsWith('audio/'))){status('Сначала убери прежнее голосовое.');return;}await upload([...e.target.files]);e.target.value='';};
$('composeForm').onsubmit=send;
 const persist=()=>localStorage.setItem('trip-composer-draft',JSON.stringify({title:$('composeTitle').value,text:$('composeText').value,type:$('composeType').value,choices:$('composeChoices').value,when:$('composeWhen').value,date:$('composeDate').value,media,requestId,editing}));
 $('composeForm').addEventListener('input',persist);$('composeForm').addEventListener('change',persist);
 try{const d=JSON.parse(localStorage.getItem('trip-composer-draft'));if(d){$('composeTitle').value=d.title;$('composeText').value=d.text;$('composeType').value=d.type;$('composeChoices').value=d.choices;$('composeWhen').value=d.when;$('composeDate').value=d.date;media=d.media||[];requestId=d.requestId||requestId;editing=d.editing;$('composeType').onchange();$('composeWhen').onchange();renderMedia();}}catch(_){}

}
function status(s){$('composeStatus').textContent=s;}
function lockComposer(locked){$('composeForm').querySelectorAll('input,textarea,select,button').forEach(node=>node.disabled=locked);$('preparedMessage').disabled=locked;}
function reset(){localStorage.removeItem("trip-composer-draft");requestId=crypto.randomUUID();editing=null;media=[];$('composeForm').reset();$('dateLabel').hidden=$('choicesLabel').hidden=true;$('composeDate').required=false;$('composeSubmit').textContent='Отправить сейчас';renderMedia();$('composeType').onchange();status('');}
async function photo(file){const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas');const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));canvas.width=bitmap.width*scale;canvas.height=bitmap.height*scale;canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.8));}
async function upload(files){if(qa){status("QA: вложения не отправляются на сервер.");return;}if(busy)return;busy=true;lockComposer(true);try{for(const file of files){status(`Загружаю ${file.name}…`);const blob=file.type.startsWith('image/')?await photo(file):file;if(blob.size>1048576)throw Error('Вложение больше 1 МБ. Выбери другую фотографию или более короткую запись.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(blob);});const mime=blob.type||(/\.m4a$/i.test(file.name)?'audio/mp4':'');const result=await TripSync.call('/api/media',{method:'POST',body:JSON.stringify({mime,data})});media.push({...result,name:file.name});renderMedia();$('composeForm').dispatchEvent(new Event('input'));}status('Вложения готовы.');}catch(e){status(e.message.includes('МБ')?e.message:'Не удалось загрузить вложение. Попробуй ещё раз.');}finally{busy=false;lockComposer(false);}}
function renderMedia(){const root=$('composeMedia');root.replaceChildren();$('attachmentCount').textContent=media.length?`${media.length} вложений`:'по желанию';for(const [i,m]of media.entries()){const row=document.createElement('div');row.className='attachment-row';const name=document.createElement('span');name.textContent=m.name||(m.mime.startsWith('image/')?'Фотография':'Голосовое');const remove=document.createElement('button');remove.type='button';remove.textContent='Убрать';remove.setAttribute('aria-label','Убрать '+name.textContent);remove.onclick=()=>{if(busy)return;media.splice(i,1);renderMedia();$('composeForm').dispatchEvent(new Event('input'));};row.append(name,remove);root.append(row);}}
function preview(){const root=$('previewBody');root.replaceChildren();const heading=document.createElement('h2');heading.id='previewTitle';heading.textContent=$('composeTitle').value||'Твоё письмо';const body=document.createElement('p');body.textContent=$('composeText').value||'Здесь будет твой текст.';root.append(heading,body);const type=$('composeType');if(type.value!=='none'){const note=document.createElement('p');note.className='preview-interaction';note.textContent=type.selectedOptions[0].textContent;root.append(note);}const gallery=document.createElement('div');gallery.className='preview-gallery';for(const m of media){const node=document.createElement(m.mime.startsWith('image/')?'img':'audio');if(node.tagName==='IMG')node.alt='Прикреплённая фотография';else node.controls=true;gallery.append(node);loadMedia(node,m,previewUrls);}root.append(gallery);$('messagePreview').showModal();}

async function send(e){e.preventDefault();if(busy)return;const choices=$('composeChoices').value.split('\n').map(s=>s.trim()).filter(Boolean),interactive=$('composeType').value;
if(interactive==='choice'&&(choices.length<2||choices.length>6)){status('Добавь от 2 до 6 вариантов ответа.');return;}
const later=$('composeWhen').value==='later',due=later?Date.parse($('composeDate').value+':00+03:00'):Date.now();if(!Number.isFinite(due)||later&&due<=Date.now()){status('Выбери время в будущем по Москве.');return;}
busy=true;lockComposer(true);status(later?'Планируем сообщение…':'Отправляем сообщение…');try{await TripSync.call('/api/messages',{method:'POST',body:JSON.stringify({id:editing||undefined,requestId,title:$('composeTitle').value,text:$('composeText').value,interactive,choices,media,due})});reset();status(later?'Сообщение запланировано.':'Отправлено. Сообщение доступно Наташе.');await list();}catch(e){status(e.message==='409'?'Сообщение уже доступно Наташе. Его нельзя изменить.':'Не удалось отправить. Текст и вложения сохранены в редакторе.');}finally{busy=false;lockComposer(false);}}
async function list(){const data=await TripSync.call('/api/messages');messages=data.messages;const root=$('sentMessages');root.innerHTML='<div class="section-heading"><p class="eyebrow">От тебя</p><h2>Сообщения</h2></div>';if(!messages.length){const empty=document.createElement('p');empty.className='empty-state';empty.textContent='Здесь будут отправленные письма и сообщения, которые ждут своего времени.';root.append(empty);}for(const m of messages){const card=document.createElement('article');card.className='sent-message';card.innerHTML=`<strong>${esc(m.title)}</strong><p>${esc(m.cancelled?'Отменено':m.due>Date.now()?'Запланировано':'Доступно Наташе')} · ${date(m.due)}</p>`;if(!m.cancelled&&m.due>Date.now()){const edit=document.createElement('button');edit.textContent='Изменить';edit.onclick=()=>{editing=m.id;media=[...m.body.media];$('composeTitle').value=m.title;$('composeText').value=m.body.text;$('composeType').value=m.body.interactive;$('composeType').onchange();$('composeChoices').value=m.body.choices.join('\n');$('composeWhen').value='later';$('composeWhen').onchange();$('composeDate').value=new Date(m.due+10800000).toISOString().slice(0,16);renderMedia();$('interactionOptions').open=true;$('composeForm').dispatchEvent(new Event('input'));$('messageComposer').scrollIntoView({block:'start'});$('composeTitle').focus();};const cancel=document.createElement('button');cancel.textContent='Отменить';cancel.onclick=async()=>{cancel.disabled=true;try{await TripSync.call('/api/messages/cancel',{method:'POST',body:JSON.stringify({id:m.id})});await list();}catch(_){status('Не удалось отменить. Проверь связь и попробуй ещё раз.');cancel.disabled=false;}};card.append(edit,cancel);}card.id='received-'+m.id;root.append(card);}}
let inbox=null,openedFromNotification=false,inboxIndex=0,loading=false;
function inboxMount(){if(inbox)return;$('scene').hidden=true;inbox=document.createElement('main');inbox.className='personal-inbox wife-feed';inbox.innerHTML='<header class="inbox-header"><div><p class="eyebrow">Наше место</p><h2>От Вани <span class="bi-icon bi-heart-fill" aria-hidden="true"></span></h2></div><button id="inboxConnect" class="icon-button" type="button" aria-label="Подключение"><span class="bi-icon bi-house-heart-fill" aria-hidden="true"></span></button></header><div class="inbox-toolbar"><button id="inboxList" type="button" disabled>Все сообщения</button><span id="inboxConnection" role="status">Проверяем связь</span></div><div id="inboxMessages"></div><nav id="inboxNavigation" hidden class="inbox-navigation" aria-label="Перелистать сообщения"><button id="inboxPrev" class="icon-button" type="button" aria-label="Предыдущее сообщение"><span class="bi-icon bi-arrow-right back-arrow" aria-hidden="true"></span></button><span id="inboxCount" aria-live="polite"></span><button id="inboxNext" class="icon-button" type="button" aria-label="Следующее сообщение"><span class="bi-icon bi-arrow-right" aria-hidden="true"></span></button></nav><dialog id="inboxListSheet" class="message-list-sheet" aria-labelledby="messageListTitle"><button id="closeInboxList" class="icon-button" type="button" aria-label="Закрыть список"><span class="bi-icon bi-x-lg" aria-hidden="true"></span></button><p class="eyebrow">Можно вернуться к каждому</p><h2 id="messageListTitle">Твои сообщения</h2><div id="inboxListItems"></div></dialog>';document.body.append(inbox);$('inboxConnect').onclick=()=>$('connectSheet').showModal();$('inboxPrev').onclick=()=>step(-1);$('inboxNext').onclick=()=>step(1);$('closeInboxList').onclick=()=>$('inboxListSheet').close();$('inboxList').onclick=()=>{const root=$('inboxListItems');root.replaceChildren();for(const [index,m]of messages.entries()){const button=document.createElement('button');button.className='message-list-item';button.setAttribute('aria-current',String(index===inboxIndex));const name=document.createElement('strong'),time=document.createElement('small');name.textContent=m.title;time.textContent=date(m.due);button.append(name,time);button.onclick=()=>{inboxIndex=index;drawInbox();$('inboxListSheet').close();};root.append(button);}if(!messages.length)root.textContent='Здесь появятся письма от Вани.';$('inboxListSheet').showModal();};let start=null;inbox.addEventListener('touchstart',e=>{if(e.target.closest('button,input,audio,.inbox-gallery,dialog'))return;start={x:e.touches[0].clientX,y:e.touches[0].clientY};},{passive:true});inbox.addEventListener('touchend',e=>{if(!start)return;const dx=e.changedTouches[0].clientX-start.x,dy=e.changedTouches[0].clientY-start.y;start=null;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.3)step(dx<0?1:-1);},{passive:true});}

function step(delta){inboxIndex=Math.max(0,Math.min(messages.length-1,inboxIndex+delta));drawInbox();}
async function loadMedia(node,m,urls=objectUrls){if(qa&&m.path){node.src=m.path;return;}try{const token=localStorage.getItem('trip-access')||window.TripNative?.getSyncAccess?.()||'';const response=await fetch('https://trip-private.ivan-s-2001.workers.dev/api/media/'+m.id,{headers:{Authorization:'Bearer '+token}});if(!response.ok)throw Error();const url=URL.createObjectURL(await response.blob());if(!node.isConnected){URL.revokeObjectURL(url);return;}urls.push(url);node.src=url;node.classList.remove('media-loading');}catch(_){if(!node.isConnected)return;const retry=document.createElement('button');retry.className='media-retry';retry.type='button';retry.textContent='Загрузить вложение ещё раз';retry.onclick=()=>{retry.replaceWith(node);loadMedia(node,m,urls);};node.replaceWith(retry);}}
function drawInbox(){objectUrls.forEach(URL.revokeObjectURL);objectUrls=[];const root=$('inboxMessages');root.replaceChildren();root.scrollTop=0;const visible=messages[inboxIndex];$('inboxNavigation').hidden=!messages.length;$('inboxList').disabled=!messages.length;$('inboxCount').textContent=messages.length?`${inboxIndex+1} из ${messages.length}`:'Пока нет сообщений';$('inboxPrev').disabled=inboxIndex===0;$('inboxNext').disabled=inboxIndex>=messages.length-1;if(!visible){const empty=document.createElement('article');empty.className='inbox-empty';empty.innerHTML='<span class="bi-icon bi-house-heart-fill" aria-hidden="true"></span><h3>Здесь тебя ждут</h3><p>Ты подключена. Когда Ваня отправит письмо, оно появится здесь.</p>';root.append(empty);}
for(const m of visible?[visible]:[]){const card=document.createElement('article');card.className='received-letter';const timestamp=document.createElement('p');timestamp.className='letter-date';timestamp.textContent=date(m.due);const title=document.createElement('h3');title.textContent=m.title;card.append(timestamp,title);const key='trip-message-'+m.id,answer=value=>TripSync.save(key,value);const content=document.createElement('div');content.className='letter-content';content.hidden=['letter','gift','hold'].includes(m.body.interactive)&&!localStorage.getItem(key);const text=document.createElement('p');text.textContent=m.body.text;content.append(text);const gallery=document.createElement('div');gallery.className='inbox-gallery';for(const f of m.body.media){const node=document.createElement(f.mime.startsWith('image/')?'img':'audio');node.className='media-loading';if(node.tagName==='AUDIO'){node.controls=true;node.preload='metadata';}else{node.alt='Фотография от Вани';node.tabIndex=0;node.setAttribute('role','button');node.setAttribute('aria-label','Открыть фотографию от Вани');const openPhoto=()=>{if(!node.src)return;$('fullPhoto').src=node.src;$('fullPhoto').alt=node.alt;$('photoViewer').showModal();};node.onclick=openPhoto;node.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openPhoto();}};}gallery.append(node);loadMedia(node,f);}content.append(gallery);card.append(content);
if(content.hidden){const open=document.createElement('button');open.className='letter-open primary';open.textContent=({letter:'Открыть письмо',gift:'Открыть подарок',hold:'Удерживай две секунды'})[m.body.interactive];const reveal=()=>{content.hidden=false;open.remove();answer('Открыла');};if(m.body.interactive==='hold'){let timer;const stop=()=>{clearTimeout(timer);open.classList.remove('holding');};const start=()=>{stop();open.classList.add('holding');timer=setTimeout(reveal,2000);};open.onpointerdown=e=>{open.setPointerCapture(e.pointerId);start();};open.onpointerup=open.onpointercancel=open.onlostpointercapture=stop;open.onkeydown=e=>{if((e.key===' '||e.key==='Enter')&&!e.repeat){e.preventDefault();start();}};open.onkeyup=open.onblur=stop;}else open.onclick=reveal;card.append(open);}else if(!localStorage.getItem(key))answer('Открыла');
if(m.body.interactive==='choice'){const group=document.createElement('div');group.className='letter-choices';const hint=document.createElement('p');hint.className='field-hint';hint.textContent='Твой ответ увидит Ваня';group.append(hint);for(const choice of m.body.choices){const button=document.createElement('button');button.textContent=choice;const selected=localStorage.getItem(key)===choice;button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected));button.onclick=()=>{answer(choice);group.querySelectorAll('button').forEach(x=>{x.classList.toggle('selected',x===button);x.setAttribute('aria-pressed',String(x===button));});};group.append(button);}card.append(group);}
if(m.body.interactive==='hug'){const button=document.createElement('button');button.className='letter-open';let count=Number(localStorage.getItem(key))||0;const label=()=>button.textContent=count?`Ещё секундочку · ${count} с`:'Обнимемся?';label();button.onclick=()=>{count++;label();answer(String(count));};card.append(button);}const signature=document.createElement('p');signature.className='letter-signature';signature.textContent='Твой Ваня';card.append(signature);card.id='received-'+m.id;root.append(card);}}

async function tick(){if(loading)return;loading=true;try{if(TripSync.getRole()==='husband'){mount();await list();}else if(TripSync.getRole()==='wife'){let data;try{data=await TripSync.call('/api/messages');localStorage.setItem('trip-received-messages',JSON.stringify(data.messages));inboxMount();$('inboxConnection').textContent='На связи';}catch(_){data={messages:JSON.parse(localStorage.getItem('trip-received-messages')||'[]')};inboxMount();$('inboxConnection').textContent='Без сети · сохранённые письма';}const previous=messages[inboxIndex]?.id;const changed=JSON.stringify(messages)!==JSON.stringify(data.messages);messages=data.messages;inboxMount();if(previous){const index=messages.findIndex(m=>m.id===previous);if(index>=0)inboxIndex=index;}if(location.hash.startsWith('#message-')&&!openedFromNotification){openedFromNotification=true;const index=messages.findIndex(m=>m.id===location.hash.slice(9));if(index>=0)inboxIndex=index;}if(changed||!$('inboxMessages').children.length||$('firstConnect'))drawInbox();}}catch(_){}finally{loading=false;}}
document.addEventListener('DOMContentLoaded',()=>{if((window.TripNative?.getAppRole?.()==='wife'||new URLSearchParams(location.search).get('app')==='wife')&&!TripSync.getRole()){inboxMount();$('inboxConnection').textContent='Ещё не подключено';$('inboxMessages').innerHTML='<article class="inbox-empty"><span class="bi-icon bi-house-heart-fill" aria-hidden="true"></span><h3>Даже когда<br>ты далеко</h3><p>Здесь будут письма, фотографии и голос Вани. Подключи приложение по его коду.</p><button id="firstConnect" class="primary" type="button">Подключиться к Ване</button></article>';$('firstConnect').onclick=()=>$('connectSheet').showModal();}setTimeout(tick,800);setInterval(()=>{if(!document.hidden)tick();},15000);window.addEventListener('online',tick);window.addEventListener('trip-connected',tick);window.addEventListener('trip-messages',tick);window.addEventListener('focus',tick);});
})();
