import assert from 'node:assert/strict';
import worker from '../server/worker.mjs';
import defaults from '../server/plans.mjs';
import {makeEnv} from './test-db.mjs';
const {env,db}=makeEnv();
const owner='1'.repeat(64),wife='2'.repeat(64),other='3'.repeat(64),otherWife='4'.repeat(64);
const call=(path,token,body)=>worker.fetch(new Request('https://trip.test/api/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token},body:body?JSON.stringify(body):undefined}),env);
const json=async r=>{assert.equal(r.status,200,await r.clone().text());return r.json();};
await json(await call('setup','',{token:owner}));await json(await call('setup','',{token:other}));const op=await json(await call('access',other,{}));await json(await call('pair','',{code:op.code,token:otherWife}));const pair=await json(await call('access',owner,{}));await json(await call('pair','',{code:pair.code,token:wife}));
const bytes=new Uint8Array(1048579);for(let i=0;i<bytes.length;i++)bytes[i]=i%251;
const start=await json(await call('media/start',owner,{mime:'application/pdf',bytes:bytes.length}));assert.equal(start.parts,3);
assert.equal((await call('media/start',wife,{mime:'audio/mp4',bytes:10})).status,403);
assert.equal((await call('media/start',owner,{mime:'audio/mp4',bytes:10485761})).status,400);
assert.equal((await call('media/'+start.id,wife)).status,404);assert.equal((await call('media/complete',owner,{id:start.id})).status,409);
assert.equal((await call('media/chunk',other,{id:start.id,part:0,data:'aGVsbG8='})).status,409);
assert.equal((await call('media/chunk',owner,{id:start.id,part:0,data:'aGVsbG8='})).status,400);
for(const part of [2,0,0,1])await json(await call('media/chunk',owner,{id:start.id,part,data:Buffer.from(bytes.slice(part*start.chunkBytes,(part+1)*start.chunkBytes)).toString('base64')}));
await json(await call('media/complete',owner,{id:start.id}));await json(await call('media/complete',owner,{id:start.id}));
const download=await call('media/'+start.id,wife);assert.equal(download.headers.get('Content-Length'),String(bytes.length));assert.deepEqual(new Uint8Array(await download.arrayBuffer()),bytes);assert.equal((await call('media/'+start.id,other)).status,404);
const plans=await json(await call('plans',owner));assert.equal(plans.plans.length,defaults.length);assert.equal(defaults.length,24);assert.ok(plans.plans.every(p=>p.messageId));assert.equal((await call('plans',wife)).status,403);
const feed=await json(await call('messages',owner));assert.equal(feed.messages.length,24);assert.equal((await json(await call('messages',wife))).messages.length,0);
const byPlan=id=>feed.messages.find(m=>m.id===plans.plans.find(p=>p.id===id).messageId);
assert.equal(byPlan('morning-11').due,Date.parse('2026-10-11T08:30:00+05:00'));assert.equal(byPlan('morning-17').due,Date.parse('2026-10-17T08:30:00+03:00'));assert.equal(byPlan('takeoff').due,Date.parse('2026-10-10T23:00:00+03:00'));assert.equal(byPlan('return-takeoff').due,Date.parse('2026-10-17T04:45:00+05:00'));
await json(await call('messages/cancel',owner,{id:byPlan('evening-11').id}));await json(await call('plans',owner));assert.equal(db.prepare('SELECT cancelled FROM messages WHERE id=?').get(byPlan('evening-11').id).cancelled,1);assert.equal(db.prepare('SELECT count(*) n FROM messages').get().n,24);
const base={title:'Arrival',text:'Test',interactive:'letter',choices:[],media:[{id:start.id,name:'test.pdf'}],due:Date.now()+10000,timeZone:'tyumen',trigger:{transition:'enter',lat:58,lon:38,radius:100000,label:'Дом'}};
assert.equal((await call('messages',owner,{...base,trigger:{...base.trigger,radius:99}})).status,400);
assert.equal((await call('messages',owner,{...base,timeZone:'invalid'})).status,400);
const custom=await json(await call('messages',owner,{...base,requestId:crypto.randomUUID()}));const geo=await json(await call('geofences',wife));assert.ok(geo.points.some(p=>p.radius===100000&&p.label==='Дом'));
const stored=db.prepare('SELECT body FROM messages WHERE id=?').get(custom.id);const zone=JSON.parse(stored.body).trigger.zone;
const event={id:crypto.randomUUID(),key:'trip-geo',value:JSON.stringify({zone,transition:'exit'}),at:Date.now()};await json(await call('events',wife,{events:[event]}));assert.ok(db.prepare('SELECT due FROM messages WHERE id=?').get(custom.id).due>Date.now());
const arrival={...event,id:crypto.randomUUID(),value:JSON.stringify({zone,transition:'enter'}),at:Date.now()};await json(await call('events',wife,{events:[arrival]}));assert.ok(db.prepare('SELECT due FROM messages WHERE id=?').get(custom.id).due<=Date.now());
const future=await json(await call('messages',owner,{...base,requestId:crypto.randomUUID()}));arrival.at=Date.now();await json(await call('events',wife,{events:[arrival]}));assert.ok(db.prepare('SELECT due FROM messages WHERE id=?').get(future.id).due>Date.now()); // same event cannot release a newly added letter
await json(await call('events',otherWife,{events:[{...arrival,id:crypto.randomUUID()}]}));assert.ok(db.prepare('SELECT due FROM messages WHERE id=?').get(future.id).due>Date.now());
const before={...arrival,id:crypto.randomUUID(),at:Date.now()};const restricted=await json(await call('messages',owner,{...base,requestId:crypto.randomUUID(),trigger:{...base.trigger,notBefore:Date.now()+60000}}));await json(await call('events',wife,{events:[before]}));assert.ok(db.prepare('SELECT due FROM messages WHERE id=?').get(restricted.id).due>Date.now());
console.log('PASS: chunked binary round trip, retries, incomplete-file privacy, room isolation, 24 automatically active plans, exact timezones/flights, cancellation persists, circle radius, enter/exit, event replay and date gates');
