import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import worker from '../server/worker.mjs';
import plans from '../server/plans.mjs';
import {makeEnv} from './test-db.mjs';
const {env,db}=makeEnv();
const digest=x=>createHash('sha256').update(x).digest('hex');
const jobs=[];const ctx={waitUntil(p){jobs.push(p)}};
const delivered=[];let pushFails=false;
const originalFetch=globalThis.fetch;
globalThis.fetch=async(url,options)=>{if(pushFails)return new Response('',{status:503});delivered.push({url,options});return new Response('{}');};
async function request(path,token,body){return worker.fetch(new Request('https://trip.test/api/'+path,{method:body?'POST':'GET',headers:token?{Authorization:'Bearer '+token}:{},body:body?JSON.stringify(body):undefined}),env,ctx)}
const json=async r=>{assert.equal(r.status,200,await r.clone().text());return r.json()};
const owner='1'.repeat(64),other='2'.repeat(64),recipient='3'.repeat(64);
await json(await request('setup',null,{token:owner}));await json(await request('setup',null,{token:owner}));await json(await request('setup',null,{token:other}));
assert.equal(db.prepare('SELECT count(*) n FROM rooms').get().n,3); // legacy + two independent spaces
const me=await json(await request('me',owner));assert.match(me.pushTopic,/^up[A-Za-z0-9_-]{12}$/);
const pairing=await json(await request('access',owner,{}));
await json(await request('pair',null,{code:pairing.code,token:recipient}));
await json(await request('pair',null,{code:pairing.code,token:recipient})); // network retry
assert.equal((await request('pair',null,{code:pairing.code,token:'4'.repeat(64)})).status,400);
const expired=await json(await request('access',owner,{}));db.prepare('UPDATE pairings SET expires=0 WHERE hash=?').run(digest(expired.code.replace('-','')));
assert.equal((await request('pair',null,{code:expired.code,token:'4'.repeat(64)})).status,400);
assert.equal((await request('setup',null,{token:recipient})).status,403);
const photo=await json(await request('media',owner,{mime:'image/jpeg',data:'aGVsbG8='}));
const voice=await json(await request('media',owner,{mime:'audio/mp4',data:'aGVsbG8='}));
const content={title:'Only for my partner',text:'Private text',interactive:'letter',choices:[],media:[photo,voice],due:Date.now()-1,requestId:crypto.randomUUID()};
const result=await json(await request('messages',owner,content));await Promise.all(jobs.splice(0));
assert.equal(delivered.length,1);assert.equal(delivered[0].options.body,'sync');assert.ok(!JSON.stringify(delivered).includes(content.title));
assert.equal(delivered[0].options.headers.Cache,'no');
assert.equal((await json(await request('messages',recipient))).messages[0].id,result.id);
assert.equal((await json(await request('messages',other))).messages.length,plans.length);
assert.equal((await request('media/'+photo.id,other)).status,404);
assert.equal((await request('messages',other,{...content,requestId:crypto.randomUUID()})).status,400);
assert.equal((await request('messages',recipient,content)).status,403);
await json(await request('events',recipient,{events:[{id:crypto.randomUUID(),key:'trip-message-'+result.id,value:'Открыла',at:Date.now()}]}));
assert.equal((await json(await request('state',owner))).state[0].value,'Открыла');assert.equal((await json(await request('state',other))).state.length,0);
const future={...content,requestId:crypto.randomUUID(),due:Date.now()+3600000};
await json(await request('messages',owner,future));assert.equal((await json(await request('messages',recipient))).messages.length,1);
await json(await request('messages',owner,{...future,id:future.requestId,due:Date.now()+7200000}));
assert.ok(db.prepare('SELECT due FROM push_jobs WHERE message_id=?').get(future.requestId).due>Date.now()+3600000);
assert.equal((await json(await request('messages/cancel',owner,{id:future.requestId}))).cancelled,true);
await worker.scheduled({},env,ctx);await Promise.all(jobs.splice(0));assert.equal(delivered.length,1);
pushFails=true;
const retry={...content,requestId:crypto.randomUUID()};await json(await request('messages',owner,retry));await Promise.all(jobs.splice(0));
assert.equal(db.prepare('SELECT sent FROM push_jobs WHERE message_id=?').get(retry.requestId).sent,0);
assert.equal(db.prepare('SELECT attempts FROM push_jobs WHERE message_id=?').get(retry.requestId).attempts,1);
pushFails=false;db.prepare('UPDATE push_jobs SET retry_at=0 WHERE message_id=?').run(retry.requestId);
await worker.scheduled({},env,ctx);await Promise.all(jobs.splice(0));assert.equal(delivered.length,2);
assert.equal(db.prepare('SELECT sent FROM push_jobs WHERE message_id=?').get(retry.requestId).sent,1);
globalThis.fetch=originalFetch;
console.log('PASS: first-run setup, idempotent pairing, expiry, isolation, photos/voice, private ntfy wake, schedule/edit/cancel, push retry');
