import {makeEnv} from './test-db.mjs';
import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
import worker from '../server/worker.mjs';
if(!globalThis.crypto) Object.defineProperty(globalThis,"crypto",{value:webcrypto});
const tokens={wife:'a'.repeat(64),husband:'b'.repeat(64)};
const {env,db}=makeEnv(tokens);
async function call(path,role,data){return worker.fetch(new Request('https://example.test/api/'+path,{method:data?'POST':'GET',headers:role?{Authorization:'Bearer '+tokens[role]}:{},body:data?JSON.stringify(data):undefined}),env)}
assert.equal((await call('state')).status,401);
assert.equal((await(await call('me','wife')).json()).role,'wife');
const event={id:'test-local-event-0001',key:'trip-choice-11-5',value:'поддержка',at:Date.now()};
assert.equal((await call('events','husband',{events:[event]})).status,403);
assert.equal((await call('events','wife',{events:[event]})).status,200);
assert.equal((await call('events','wife',{events:[event]})).status,200);
assert.equal(db.prepare('SELECT count(*) AS n FROM events').get().n,1);
assert.equal((await(await call('state','husband')).json()).state[0].value,'поддержка');
await call('events','wife',{events:[{...event,id:'test-local-event-0002',value:'тишина',at:event.at-1000}]});assert.equal(db.prepare('SELECT value FROM state WHERE key=?').get(event.key).value,'поддержка');
assert.equal((await call('events','wife',{events:[{...event,key:'unknown'}]})).status,400);
assert.equal((await call('events','wife',{events:[{...event,value:'x'.repeat(2001)}]})).status,400);
console.log('PASS: role authorization, write/read, retries, stale updates, validation');
