const {chromium:playwright}=require(process.env.TRIP_PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
(async()=>{
 const http=require('node:http'),fs=require('node:fs'),path=require('node:path');const server=http.createServer((req,res)=>{let f=path.join(path.resolve(__dirname,'..'),new URL(req.url,'http://local').pathname);if(f.endsWith('/'))f+='index.html';try{const type={'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.jpg':'image/jpeg'}[path.extname(f)]||'application/octet-stream';res.writeHead(200,{'Content-Type':type});res.end(fs.readFileSync(f));}catch(_){res.writeHead(404);res.end();}});await new Promise(r=>server.listen(8765,'127.0.0.1',r));
 const browser=await playwright.launch({executablePath:process.env.TRIP_CHROMIUM||undefined,args:['--no-sandbox','--disable-dev-shm-usage'],headless:true});
 const errors=[];const samples=[{id:'11111111-1111-4111-8111-111111111111',title:'Когда захочется домой',due:Date.now()-1000,body:{text:'Мы с котами уже скучаем.\n\nНе торопись. Завари чай, устройся поудобнее и знай: дома тебя очень ждут.',interactive:'letter',choices:[],media:[]}},{id:'22222222-2222-4222-8222-222222222222',title:'А вечером?',due:Date.now()-500,body:{text:'Выбирай, что будем делать, когда вернёшься.',interactive:'choice',choices:['Фильм и обниматься','Чай и разговоры'],media:[]}},{id:'33333333-3333-4333-8333-333333333333',title:'Две секунды рядом',due:Date.now()-200,body:{text:'Вот и обнялись.',interactive:'hold',choices:[],media:[]}}];
 async function pageFor(role,size={width:375,height:812}){const context=await browser.newContext({viewport:size,serviceWorkers:'block'});await context.addInitScript(role=>{if(role){localStorage.setItem('trip-access','a'.repeat(64));localStorage.setItem('trip-role',role);localStorage.setItem('trip-room','fixture');}},role);const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));let sent=[];let offline=false;
 await page.route('https://ntfy.sh/**',r=>r.abort());await page.route('https://trip-private.ivan-s-2001.workers.dev/api/**',async r=>{if(offline)return r.abort();const req=r.request(),path=new URL(req.url()).pathname;let data={};if(path==='/api/me')data={role,roomId:'fixture',pushTopic:''};if(path==='/api/state')data={state:[],events:[]};if(path==='/api/messages'){if(req.method()==='POST'){sent.push(req.postDataJSON());data={id:sent.at(-1).requestId};}else data={messages:role==='wife'?samples:[]};}if(path==='/api/media')data={id:'synthetic-photo',mime:'image/jpeg'};if(path==='/api/events')data={accepted:req.postDataJSON().events.map(x=>x.id)};await r.fulfill({json:data,headers:{'Access-Control-Allow-Origin':'*'}});});await page.goto('http://127.0.0.1:8765/?app='+ (role||'wife'));return {page,context,sent,setOffline:()=>offline=true};}
 const owner=await pageFor('husband'),p=owner.page;await p.locator('#composeTitle').waitFor();await p.locator('#composeTitle').fill('Когда захочется домой');await p.locator('#composeText').fill(samples[0].body.text);await p.locator('#composePreview').click();await p.locator('#messagePreview[open]').waitFor();assert.equal(owner.sent.length,0);await p.screenshot({path:'/tmp/trip-preview.png'});await p.locator('#closePreview').click();await p.reload();await p.locator('#composeTitle').waitFor();assert.equal(await p.locator('#composeTitle').inputValue(),'Когда захочется домой');await p.screenshot({path:'/tmp/trip-owner-phone.png'});assert.equal(await p.evaluate(()=>document.querySelector('#husbandDashboard').scrollWidth>innerWidth),false);
 await p.locator('.compose-options').first().locator('summary').click();await p.locator('#composePhotos').setInputFiles({name:'test.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAGUlEQVR4nGO8c2IfAymAiSTVoxpGNQwpDQB78wKCJ437OQAAAABJRU5ErkJggg==','base64')});await p.getByText('Вложения готовы.',{exact:true}).waitFor();await p.locator('#composeMedia button').click();assert.equal(JSON.parse(await p.evaluate(()=>localStorage.getItem('trip-composer-draft'))).media.length,0);
 await p.locator('#composeSubmit').click();await p.getByText('Отправлено. Сообщение доступно Наташе.',{exact:true}).waitFor();assert.equal(owner.sent.length,1);assert.equal(owner.sent[0].title,'Когда захочется домой');assert.equal(owner.sent[0].media.length,0);
 const desktop=await pageFor('husband',{width:1440,height:1000});await desktop.page.locator('#composeTitle').waitFor();await desktop.page.screenshot({path:'/tmp/trip-owner-desktop.png'});assert.equal(await desktop.page.evaluate(()=>document.querySelector('#husbandDashboard').scrollWidth>innerWidth),false);
 const wife=await pageFor('wife'),w=wife.page;await w.getByRole('button',{name:'Открыть письмо',exact:true}).waitFor();await w.screenshot({path:'/tmp/trip-wife-closed.png'});await w.getByRole('button',{name:'Открыть письмо',exact:true}).click();await w.screenshot({path:'/tmp/trip-wife-letter.png'});await w.locator('#inboxNext').click();await w.getByRole('button',{name:'Чай и разговоры',exact:true}).click();assert.equal(await w.getByRole('button',{name:'Чай и разговоры',exact:true}).getAttribute('aria-pressed'),'true');await w.locator('#inboxPrev').click();assert.equal(await w.getByRole('button',{name:'Открыть письмо',exact:true}).count(),0);
 await w.locator('#inboxList').click();await w.locator('.message-list-item').nth(2).click();const hold=w.getByRole('button',{name:'Удерживай две секунды'});await hold.focus();await w.keyboard.down('Space');await w.waitForTimeout(2200);await w.keyboard.up('Space');assert.equal(await w.locator('.letter-content').isVisible(),true);wife.setOffline();await w.evaluate(()=>dispatchEvent(new Event('trip-messages')));await w.getByText('Без сети · сохранённые письма',{exact:true}).waitFor();assert.equal(await w.evaluate(()=>document.querySelector('.wife-feed').scrollWidth>innerWidth),false);
 await w.setViewportSize({width:812,height:375});await w.screenshot({path:'/tmp/trip-wife-landscape.png'});await w.emulateMedia({reducedMotion:'reduce'});await w.setViewportSize({width:375,height:812});await w.addStyleTag({content:'.letter-content>p{font-size:26px}.received-letter h3{font-size:48px}.inbox-header h2{font-size:42px}'});assert.equal(await w.evaluate(()=>document.querySelector('.wife-feed').scrollWidth>innerWidth),false);assert.equal(await w.locator('#inboxNext').isVisible(),true);
 const welcome=await pageFor('');await welcome.page.waitForTimeout(1500);await welcome.page.locator('#firstConnect').waitFor();await welcome.page.screenshot({path:'/tmp/trip-wife-welcome.png'});await welcome.page.locator('#firstConnect').click();await welcome.page.locator('#connectSheet[open]').waitFor();await welcome.page.screenshot({path:'/tmp/trip-connect.png'});
 assert.deepEqual(errors,[]);console.log('PASS: browser preview, draft restore, upload/remove persistence, send, list, opened letter, choice, keyboard hold, offline feed, mobile/desktop/landscape and reduced motion; no JS errors');await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
