export default [
  {
    "id": "leave-rybinsk",
    "title": "Уезд из Рыбинска",
    "text": "Тучка моя, счастливой дороги. Мы с Чопой и Нафаней уже скучаем. Дом едет с тобой — в этих маленьких письмах.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "exit",
    "point": "rybinsk",
    "radius": 20,
    "timeZone": "moscow",
    "date": "",
    "group": "route",
    "afterPlan": null,
    "notBefore": "2026-10-10T00:00:00+03:00",
    "notAfter": "2026-10-12T00:00:00+05:00"
  },
  {
    "id": "arrive-airport",
    "title": "Приезд в аэропорт",
    "text": "Ты добралась до аэропорта. Выдохни, попей воды и проверь, что документы и телефон рядом. Я с тобой, солнышко.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "enter",
    "point": "svo",
    "radius": 20,
    "timeZone": "moscow",
    "date": "",
    "group": "route",
    "afterPlan": null,
    "notBefore": "2026-10-10T00:00:00+03:00",
    "notAfter": "2026-10-12T00:00:00+05:00"
  },
  {
    "id": "takeoff",
    "title": "Вылет",
    "text": "Мягкого полёта, любимая. Устройся поудобнее и отдохни. Скоро будет новое маленькое письмо от нас.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "later",
    "point": "svo",
    "radius": 20,
    "timeZone": "moscow",
    "date": "2026-10-10T23:00",
    "group": "route",
    "afterPlan": null,
    "notBefore": "2026-10-10T00:00:00+03:00",
    "notAfter": "2026-10-12T00:00:00+05:00"
  },
  {
    "id": "arrive-tyumen",
    "title": "Прилёт в Тюмень",
    "text": "С прилётом, моя тучка. Самолёт позади, осталось немного дороги. Напиши, как ты, когда будет удобно.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "enter",
    "point": "tjm",
    "radius": 20,
    "timeZone": "tyumen",
    "date": "",
    "group": "route",
    "afterPlan": null,
    "notBefore": "2026-10-10T00:00:00+03:00",
    "notAfter": "2026-10-12T00:00:00+05:00"
  },
  {
    "id": "arrive-kurgan",
    "title": "Приезд в Курган",
    "text": "Ура, ты добралась! Обнимаю тебя через все километры. Теперь можно выдохнуть и немного отдохнуть.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "enter",
    "point": "kurgan",
    "radius": 20,
    "timeZone": "tyumen",
    "date": "",
    "group": "route",
    "afterPlan": null,
    "notBefore": "2026-10-10T00:00:00+03:00",
    "notAfter": "2026-10-12T00:00:00+05:00"
  },
  {
    "id": "return-kurgan",
    "title": "Обратная дорога · из Кургана",
    "text": "Ты едешь домой. Мы с котами ждём тебя всё сильнее. Не торопись — самое главное, чтобы дорога была спокойной.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "exit",
    "point": "kurgan",
    "radius": 20,
    "timeZone": "tyumen",
    "date": "",
    "group": "route",
    "afterPlan": null,
    "notBefore": "2026-10-16T00:00:00+05:00",
    "notAfter": "2026-10-19T00:00:00+03:00"
  },
  {
    "id": "return-airport",
    "title": "Обратная дорога · аэропорт Тюмени",
    "text": "Остался ещё один перелёт, а потом мы будем ближе. Мягкой дороги домой, солнышко.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "enter",
    "point": "tjm",
    "radius": 20,
    "timeZone": "tyumen",
    "date": "",
    "group": "route",
    "afterPlan": null,
    "notBefore": "2026-10-16T00:00:00+05:00",
    "notAfter": "2026-10-19T00:00:00+03:00"
  },
  {
    "id": "return-takeoff",
    "title": "Обратный вылет · SU 1503",
    "text": "Мягкого полёта домой, любимая. Ещё немного, и мы будем ближе. Я очень тебя жду.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "later",
    "date": "2026-10-17T04:45",
    "timeZone": "tyumen",
    "group": "route"
  },
  {
    "id": "return-moscow",
    "title": "Прилёт в Москву",
    "text": "С прилётом, солнышко. Самолёт позади. Пусть оставшаяся дорога до дома будет лёгкой. Мы с котами уже ждём.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "enter",
    "point": "svo",
    "radius": 20,
    "timeZone": "moscow",
    "date": "",
    "group": "route",
    "afterPlan": null,
    "notBefore": "2026-10-17T00:00:00+03:00",
    "notAfter": "2026-10-19T00:00:00+03:00"
  },
  {
    "id": "return-home",
    "title": "Возвращение в Рыбинск",
    "text": "Ты вернулась в Рыбинск. Можно больше не обниматься через экран. Мы с Чопой и Нафаней очень тебя ждали.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "enter",
    "point": "rybinsk",
    "radius": 100,
    "timeZone": "moscow",
    "date": "",
    "group": "route",
    "pointName": "Рыбинск",
    "afterPlan": null,
    "notBefore": "2026-10-17T00:00:00+03:00",
    "notAfter": "2026-10-19T00:00:00+03:00"
  },
  {
    "id": "morning-11",
    "title": "11 октября · Доброе утро",
    "text": "Доброе утро, тучка моя. Пусть первый день в Кургане будет спокойным. Мы с котами рядом — просто немного дальше обычного.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "later",
    "date": "2026-10-11T08:30",
    "timeZone": "kurgan",
    "group": "daily"
  },
  {
    "id": "evening-11",
    "title": "11 октября · Спокойной ночи",
    "text": "Первый день позади. Ты молодец. Отложи дела, устройся поудобнее и почувствуй, как я тебя обнимаю. Спокойной ночи.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "later",
    "date": "2026-10-11T21:30",
    "timeZone": "kurgan",
    "group": "daily"
  },
  {
    "id": "morning-12",
    "title": "12 октября · Доброе утро",
    "text": "Доброе утро, солнышко. Сначала вода и завтрак, потом все дела. Обнимаю тебя и желаю хорошего дня.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "later",
    "date": "2026-10-12T08:30",
    "timeZone": "kurgan",
    "group": "daily"
  },
  {
    "id": "evening-12",
    "title": "12 октября · Спокойной ночи",
    "text": "Спокойной ночи, тучка моя. Мы с котами отправляем тебе всё наше тепло. Завтра будет новый день и новое письмо.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "later",
    "date": "2026-10-12T21:30",
    "timeZone": "kurgan",
    "group": "daily"
  },
  {
    "id": "morning-13",
    "title": "13 октября · Доброе утро",
    "text": "Доброе утро, любимая. Ещё один день начался, и я снова хочу сказать, как сильно тебя люблю.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "later",
    "date": "2026-10-13T08:30",
    "timeZone": "kurgan",
    "group": "daily"
  },
  {
    "id": "evening-13",
    "title": "13 октября · Спокойной ночи",
    "text": "Ещё один день ближе к дому. Если устала, сегодня можно ничего больше не успевать. Отдыхай, любимая.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "later",
    "date": "2026-10-13T21:30",
    "timeZone": "kurgan",
    "group": "daily"
  },
  {
    "id": "morning-14",
    "title": "14 октября · Доброе утро",
    "text": "Доброе утро. Половина поездки уже позади. Каждый день мы становимся чуть ближе к нашей встрече.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "later",
    "date": "2026-10-14T08:30",
    "timeZone": "kurgan",
    "group": "daily"
  },
  {
    "id": "evening-14",
    "title": "14 октября · Спокойной ночи",
    "text": "Половина позади, и теперь только ближе. Я скучаю по твоему голосу и нашему обычному вечеру. Спокойной ночи.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "later",
    "date": "2026-10-14T21:30",
    "timeZone": "kurgan",
    "group": "daily"
  },
  {
    "id": "morning-15",
    "title": "15 октября · Доброе утро",
    "text": "Доброе утро, моя тучка. Уже совсем скоро будем пить чай дома и рассказывать друг другу всё подряд.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "later",
    "date": "2026-10-15T08:30",
    "timeZone": "kurgan",
    "group": "daily"
  },
  {
    "id": "evening-15",
    "title": "15 октября · Спокойной ночи",
    "text": "Последний обычный вечер поездки. Скоро это маленькое расстояние закончится. Обнимаю тебя крепко-крепко.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "later",
    "date": "2026-10-15T21:30",
    "timeZone": "kurgan",
    "group": "daily"
  },
  {
    "id": "morning-16",
    "title": "16 октября · Доброе утро",
    "text": "Доброе утро, любимая. Пять лет с того дня, как мы стали «мы». Спасибо, что ты есть в моей жизни. Люблю тебя.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "later",
    "date": "2026-10-16T08:30",
    "timeZone": "kurgan",
    "group": "daily"
  },
  {
    "id": "evening-16",
    "title": "16 октября · Спокойной ночи",
    "text": "Пять лет вместе. И я всё так же хочу быть рядом с тобой. Спасибо за наше «мы». Спокойной ночи, любимая.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "later",
    "date": "2026-10-16T21:30",
    "timeZone": "kurgan",
    "group": "daily"
  },
  {
    "id": "morning-17",
    "title": "17 октября · Доброе утро",
    "text": "Доброе утро, солнышко. Сегодня домой. Мы с Чопой и Нафаней ждём тебя. Пусть вся дорога будет лёгкой.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "later",
    "date": "2026-10-17T08:30",
    "timeZone": "moscow",
    "group": "daily"
  },
  {
    "id": "evening-17",
    "title": "17 октября · Спокойной ночи",
    "text": "Ты вернулась к нам. Спасибо, что открывала эти маленькие письма. А теперь можно просто быть рядом. Люблю тебя.",
    "interactive": "letter",
    "choices": [],
    "media": [],
    "when": "later",
    "date": "2026-10-17T21:30",
    "timeZone": "moscow",
    "group": "daily"
  }
];
