CREATE TABLE IF NOT EXISTS rooms(id TEXT PRIMARY KEY,topic TEXT NOT NULL,created INTEGER NOT NULL);
INSERT OR IGNORE INTO rooms VALUES('legacy','up'||lower(hex(randomblob(6))),0);
CREATE TABLE IF NOT EXISTS access(hash TEXT PRIMARY KEY,role TEXT NOT NULL CHECK(role IN ('wife','husband')),room_id TEXT NOT NULL DEFAULT 'legacy');
CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,key TEXT NOT NULL,value TEXT NOT NULL,at INTEGER NOT NULL,received INTEGER NOT NULL,room_id TEXT NOT NULL DEFAULT 'legacy');
CREATE TABLE IF NOT EXISTS state(room_id TEXT NOT NULL,key TEXT NOT NULL,value TEXT NOT NULL,at INTEGER NOT NULL,PRIMARY KEY(room_id,key));
CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY,title TEXT NOT NULL,body TEXT NOT NULL,due INTEGER NOT NULL,created INTEGER NOT NULL,cancelled INTEGER NOT NULL DEFAULT 0,room_id TEXT NOT NULL DEFAULT 'legacy');
CREATE TABLE IF NOT EXISTS media(id TEXT PRIMARY KEY,mime TEXT NOT NULL,data TEXT NOT NULL,created INTEGER NOT NULL,room_id TEXT NOT NULL DEFAULT 'legacy',bytes INTEGER NOT NULL DEFAULT 0,parts INTEGER NOT NULL DEFAULT 0,complete INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS media_chunks(media_id TEXT NOT NULL,part INTEGER NOT NULL,data TEXT NOT NULL,PRIMARY KEY(media_id,part));
CREATE TABLE IF NOT EXISTS pairings(hash TEXT PRIMARY KEY,room_id TEXT NOT NULL,expires INTEGER NOT NULL,used_hash TEXT);
CREATE TABLE IF NOT EXISTS push_jobs(message_id TEXT PRIMARY KEY,room_id TEXT NOT NULL,due INTEGER NOT NULL,sent INTEGER NOT NULL DEFAULT 0,attempts INTEGER NOT NULL DEFAULT 0,retry_at INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS messages_room_due ON messages(room_id,cancelled,due);
CREATE INDEX IF NOT EXISTS events_room_at ON events(room_id,at);
CREATE INDEX IF NOT EXISTS pending_push ON push_jobs(sent,due,retry_at);

CREATE TABLE IF NOT EXISTS plans (room_id TEXT NOT NULL, id TEXT NOT NULL, body TEXT NOT NULL, message_id TEXT, PRIMARY KEY(room_id,id));

CREATE TABLE IF NOT EXISTS geo_receipts (room_id TEXT NOT NULL,event_id TEXT NOT NULL,PRIMARY KEY(room_id,event_id));
