CREATE TABLE IF NOT EXISTS access(hash TEXT PRIMARY KEY,role TEXT NOT NULL CHECK(role IN ('wife','husband')));
CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,key TEXT NOT NULL,value TEXT NOT NULL,at INTEGER NOT NULL,received INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS state(key TEXT PRIMARY KEY,value TEXT NOT NULL,at INTEGER NOT NULL);
