CREATE TABLE IF NOT EXISTS access(hash TEXT PRIMARY KEY,role TEXT NOT NULL CHECK(role IN ('wife','husband')));
CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,key TEXT NOT NULL,value TEXT NOT NULL,at INTEGER NOT NULL,received INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS state(key TEXT PRIMARY KEY,value TEXT NOT NULL,at INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY,title TEXT NOT NULL,body TEXT NOT NULL,due INTEGER NOT NULL,created INTEGER NOT NULL,cancelled INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS media(id TEXT PRIMARY KEY,mime TEXT NOT NULL,data TEXT NOT NULL,created INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS messages_due ON messages(cancelled,due);
