ALTER TABLE media ADD COLUMN bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE media ADD COLUMN parts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE media ADD COLUMN complete INTEGER NOT NULL DEFAULT 1;
CREATE TABLE IF NOT EXISTS media_chunks(media_id TEXT NOT NULL,part INTEGER NOT NULL,data TEXT NOT NULL,PRIMARY KEY(media_id,part));

CREATE TABLE IF NOT EXISTS geo_receipts (room_id TEXT NOT NULL,event_id TEXT NOT NULL,PRIMARY KEY(room_id,event_id));
